### ISSUE TITLE
Building with Qt4 fails

### ISSUE THREAD

**Issue by dirk-olmes** [psi-plus/psi-plus-snapshots#7]
Hi,

starting with release 452, I cannot build on Qt4 any more:

Checking for Psi Plugin support ...

        !!!!!!!!!!!!!! WARNING !!!!!!!!!!!!!!!
        PLUGIN SUPPORT IS STILL UNFINISHED !!!
        THE PLUGIN INTERFACE /WILL/ CHANGE !!!
        USE AT YOUR OWN RISK !!!
 yes
Generating .prl files ... ok
WARNING: /var/tmp/portage/net-im/psi-plus-0.16.452/work/psi-plus-snapshots-0.16.452/psi.pro:3: Unable to find file for inclusion /conf.pri
sh: /iris/conf.pri: No such file or directory

Good, your configure finished.  Now run /usr/bin/gmake.

It says configure finished but the error above makes me think that something is wrong ... Compile fails with:

make[1]: Leaving directory '/var/tmp/portage/net-im/psi-plus-0.16.452/work/psi-plus-snapshots-0.16.452/iris'
Makefile:40: recipe for target 'sub-iris-make_default' failed
make: *** [sub-iris-make_default] Error 2
make: *** Waiting for unfinished jobs....
WARNING: target.path is not defined: install target not created

WARNING: sharedfiles.path is not defined: install target not created

I'm no expert in the whole qmake topic, can anyone help, please?

**Comment by Ri0n** [comment]
should work now

**Comment by dirk-olmes** [comment]
Just tested with the latest available release (457) ... same error still

**Comment by Ri0n** [comment]
you have to try official ebuild then

**Comment by dirk-olmes** [comment]
Well the official ebuild is anicent, this is why I'm rolling my own.

Comparing the changes in the build system, I was able to isolate the differences in the build files (see https://bpaste.net/show/8a6d369eb2fd). I guess these changes were pulled from upstream but I'm really wondering how upstream can bulid using those build files? Or is it just Qt4 compatability that's broken and upstream does not care about it any more?

**Comment by Ri0n** [comment]
official is in my overlay
layman -a rion

**Comment by dirk-olmes** [comment]
Ok it was clearly a problem with my local setup.

The 0.16.457 snapshot does not build (does not even configure correctly) but git HEAD builds just fine.
